title: "FKOMINFO UNIGA Expo"
description: "Katalog Pameran Karya & Inovasi Mahasiswa Fakultas Komunikasi dan Informasi di Universitas Garut"
baseurl: "/expo" 
url: "https://rit-base.github.io" 

# Konfigurasi Collections (Agar folder _karya terbaca)
collections:
  karya:
    output: true
    permalink: /karya/:slug/

# Pengaturan Build
markdown: kramdown
theme: minima # Override dari layout minima
plugins:
  - jekyll-feed